-- CreateEnum
CREATE TYPE "IssueTag" AS ENUM ('DESIGN', 'FRONTEND_CODING', 'BACKEND_CODING', 'MARKETING', 'PRODUCT', 'BUG', 'DOCUMENTATION', 'RESEARCH', 'TESTING', 'OPERATIONS', 'FEATURE');

-- AlterTable
ALTER TABLE "Issue" ADD COLUMN "tag" "IssueTag" NOT NULL DEFAULT 'FEATURE';
